import "./globals.css";
// import Navbar from "@/component/Navbar";
// import { usePathname } from "next/navigation";
import ClientLayout from "@/app/component/ClinetLayout";
import SocketProvider from "./context/SocketProvider";
import ErrorBoundary from "./component/ErrorBoundry";
import ToastProvider from "./providers/ToastProvider";

export const metadata = {
  title: "SkillSwap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  // const pathName = usePathname();

  // const noNavbarRoutes = ['/SignUp', 'Login'];

  // const showNavbar = !noNavbarRoutes.includes(pathName);

  return (
    <html lang="en">
      <body style={{ margin: 0, backgroundColor: "#f9f9f9", color: "#000" }}>
        {/* {showNavbar && <Navbar />}
        {children} */}
        <ErrorBoundary>
          <SocketProvider>
            <ClientLayout> {children} 
              <ToastProvider />
            </ClientLayout>
          </SocketProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
